name: Golang workshop

on:
  push:
    branches:
      - '**'

env:
  GOLANG_VERSION: 1.21.x
  DOCKER_REPOSITORY: sjambon
  DOCKER_IMAGE: aelm-workshop-24

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ env.GOLANG_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Build
        run: go build
        working-directory: workshop-service