name: Golang workshop

on:
  push:
    branches:
      - '**'

env:
  GOLANG_VERSION: 1.21.x
  DOCKER_REPOSITORY: sjambon
  DOCKER_IMAGE: aelm-workshop-24

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ env.GOLANG_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Build
        run: go build -o ../bin/workshop -v ./...
        working-directory: workshop-service

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{env.DOCKER_REPOSITORY}}/${{env.DOCKER_IMAGE}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}